#menu
menu:
  Karya: /karya
  Tentang: /tentang

# social profile at the footer/bottom
place: https://www.google.com/search?q=kendal+jawa+tengah
github: https://github.com/adisaktijrs
instagram: https://www.instagram.com/adisaktijrs/
twitter: https://twitter.com/adisaktijrs

# js
nanobar: /js/nanobar.min.js

# favicon
favicon: /images/favicon.png

# main image
main: /images/epic.jpg

article:
  thumbnail: true

# DISQUS comments
disqus_enabled: true
disqus_shortname: https-adisaktijrs-github-io
