#title in header
title: "Hi Folks."

#main info
#owner
owner: "Saya Adi Sakti Jrs"
info: "Seorang pelajar dan pengembang web"
#description
desc: "Saya menyukai desain, novel, dan pengembangan web. Di sini saya akan membagikan tulisan berupa cerita, opini, dan sekaligus dokumentasi pribadi ketika saya sedang belajar hal baru. Selamat membaca kawan! 😁"

#menu
menu:
  Karya: /karya
  Tentang: /tentang

#index/main page max show posts (in number)
max_post: 3

# social profile at the footer/bottom
place: https://www.google.com/search?q=kendal+jawa+tengah
github: https://github.com/adisaktijrs
instagram: https://www.instagram.com/adisaktijrs/
twitter: https://twitter.com/adisaktijrs

# js
nanobar: /js/nanobar.min.js

# favicon
favicon: /images/favicon.png

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: https-adisaktijrs-github-io
